# Generated by Django 4.1.1 on 2023-01-24 13:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.FileField(null=True, upload_to='Media/About_item')),
                ('text', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Media/')),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('title_uz', models.CharField(max_length=50)),
                ('title_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='Media/Sertificat')),
                ('about_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.about_item')),
            ],
        ),
    ]
